"""Molecular sieve dehydration: identical module to the sibling ethanol-
design-opensource repo's own `dehydration.py` (see `properties.py`'s
docstring for why this reuse is warranted -- anhydrous fuel-ethanol
dehydration is the same physical process regardless of feedstock
origin). Distillation stops at the ethanol-water azeotrope (~95.5 wt%
ethanol, see `properties.py`), but fuel ethanol needs to be nominally
anhydrous -- India's BIS IS 15464:2004 caps water at 0.8% v/v (this
module's own default target, tighter than the ~1 wt% water ASTM D4806
implies for the US denatured-blend spec). Vapor-phase pressure-swing
adsorption (VPSA) on 3A zeolite is the standard modern fuel-ethanol
technology for this step: unlike 4A sieve (used for natural gas
dehydration in the sibling lng-design-opensource repo's
`molecular_sieve.py`, whose GPSA Ch. 20 two-bed structure this module
reuses), 3A's smaller ~3-angstrom pore excludes the larger ethanol
molecule while still admitting water -- the property that makes selective
adsorption possible at all (e.g. the OIM Chemical / SKJ Group technical
notes on 3A sieve ethanol dehydration; Kupiec, Rakoczy & Zapotoczny-
Pieniek, "Ethanol-water adsorption on commercial 3A zeolites: kinetic and
thermodynamic data", Brazilian J. Chem. Eng., 2011). Dynamic working
capacity in ethanol vapor service is commonly reported as 3-5 wt% (far
below 4A's 10-13% for natural gas, since it is water uptake from a
mostly-condensable ethanol vapor stream rather than a dilute trace in a
non-adsorbing gas), regenerated by a pressure/thermal swing at 200-250 C
-- both figures from the same sources, this module defaults to their
midpoints (4% capacity, 225 C regeneration) and takes both as overridable
inputs. Industrial full-scale VPSA units commonly cite a 4-12 h adsorption
cycle (this module's own default, 8 h, the midpoint); smaller patent-
literature designs report much faster minutes-scale cycles at a
correspondingly smaller bed -- both are real, just different design
points, so `adsorption_time_h` is left fully overridable rather than
treated as one universal constant.

Regeneration duty sums SENSIBLE heat (to raise the purge stream to
regeneration temperature) and LATENT heat (to actually desorb water
from the zeolite, 4.19 MJ/kg water -- Interra Global's published mSORB
3A EDG heat-of-adsorption figure). This fix was found via vendor
research on the sibling ethanol-design-opensource repo (see that
repo's docs/VALIDATION.md for the full finding: latent heat turns out
to be ~90% of total duty, not a minor correction) and is propagated
here unchanged, since the underlying adsorption physics doesn't depend
on which feedstock produced the ethanol."""
from __future__ import annotations

import math
from dataclasses import dataclass

import CoolProp.CoolProp as CP

BIS_IS_15464_MAX_WATER_VOL_FRAC = 0.008  # India anhydrous fuel-ethanol spec
HEAT_OF_ADSORPTION_MJ_PER_KG_WATER = 4.19  # 1,800 BTU/lb H2O, Interra Global mSORB 3A EDG datasheet


@dataclass
class DehydrationBedResult:
    water_removed_per_cycle_kg: float
    bed_mass_kg: float
    bed_volume_m3: float
    bed_diameter_m: float
    bed_height_m: float
    n_beds: int
    regen_ethanol_vapor_flow_kg_s: float
    regen_sensible_duty_kW: float
    regen_latent_duty_kW: float
    regen_heater_duty_kW: float
    meets_bis_spec: bool
    height_to_diameter_ratio: float
    recommend_parallel_vessels: bool


def size_dehydration_bed(
    ethanol_vapor_mass_flow_kg_s: float,
    inlet_water_mass_frac: float,
    outlet_water_vol_frac: float = BIS_IS_15464_MAX_WATER_VOL_FRAC,
    adsorption_time_h: float = 8.0,
    regen_time_h: float = 4.0,
    cooldown_time_h: float = 1.0,
    design_velocity_m_s: float = 0.30,
    vapor_density_kg_m3: float = 1.5,
    working_capacity_wt_pct: float = 4.0,
    sieve_bulk_density_kg_m3: float = 700.0,
    regen_purge_fraction_of_feed: float = 0.20,
    feed_temperature_K: float = 373.15,
    regen_temperature_C: float = 225.0,
    min_bed_height_m: float = 0.8,
) -> DehydrationBedResult:
    """Same two-part sizing structure as the sibling LNG repo's natural-gas
    molecular-sieve module (design superficial velocity sets diameter;
    water duty / working capacity sets adsorbent mass, hence height at that
    diameter), with the same "pancake bed" guard against an
    inconsistent, physically implausible combination of the two -- see
    that module's docstring, and docs/VALIDATION.md here, for why both
    paths are kept independent rather than one silently overriding the
    other.

    `outlet_water_vol_frac` is checked against `inlet_water_mass_frac`
    purely as a feasibility flag (adsorption always removes water, so any
    positive `working_capacity_wt_pct` drives outlet water toward the
    target); the actual outlet purity a real bed achieves depends on
    breakthrough-curve behaviour this conceptual mass-balance model does
    not simulate.
    """
    if not 0 < inlet_water_mass_frac < 0.20:
        raise ValueError("inlet_water_mass_frac outside a plausible near-azeotrope range (0-20%)")

    water_removed_kg = ethanol_vapor_mass_flow_kg_s * 3600.0 * adsorption_time_h * inlet_water_mass_frac
    bed_mass_kg = water_removed_kg / (working_capacity_wt_pct / 100.0)
    bed_volume_m3 = bed_mass_kg / sieve_bulk_density_kg_m3

    vol_flow_m3_s = ethanol_vapor_mass_flow_kg_s / vapor_density_kg_m3
    required_area = vol_flow_m3_s / design_velocity_m_s
    diameter_m = math.sqrt(4.0 * required_area / math.pi)
    bed_height_m = bed_volume_m3 / required_area

    if bed_height_m < min_bed_height_m:
        raise ValueError(
            f"Computed bed height ({bed_height_m:.2f} m) is below the practical minimum "
            f"({min_bed_height_m:.2f} m) for a mass-transfer zone to develop -- the "
            f"velocity-sized diameter ({diameter_m:.2f} m) is oversized relative to the "
            "water-removal duty. Increase design_velocity_m_s to shrink the diameter."
        )

    n_beds = 2 if (regen_time_h + cooldown_time_h) <= adsorption_time_h else 3

    regen_flow_kg_s = regen_purge_fraction_of_feed * ethanol_vapor_mass_flow_kg_s
    cp_ethanol_vapor = CP.PropsSI("Cpmass", "T", feed_temperature_K, "P", 101325.0, "Ethanol")
    sensible_duty_kW = regen_flow_kg_s * cp_ethanol_vapor * (regen_temperature_C + 273.15 - feed_temperature_K) / 1000.0
    latent_duty_kW = water_removed_kg * HEAT_OF_ADSORPTION_MJ_PER_KG_WATER * 1000.0 / (regen_time_h * 3600.0)
    regen_duty_kW = sensible_duty_kW + latent_duty_kW

    # A very slender (tall, narrow) single vessel is a real geometry, not a modeling
    # error, but past roughly 8:1 height:diameter, most conceptual-design practice
    # (consistent with the pressure-drop/support reasoning behind the sibling LNG
    # repo's own vessel-geometry guard in vessels.py) would split the duty across
    # multiple parallel, shorter vessels instead -- flagged here, not silently sized.
    aspect_ratio = bed_height_m / diameter_m
    recommend_parallel = aspect_ratio > 8.0

    return DehydrationBedResult(
        water_removed_per_cycle_kg=water_removed_kg,
        bed_mass_kg=bed_mass_kg,
        bed_volume_m3=bed_volume_m3,
        bed_diameter_m=diameter_m,
        bed_height_m=bed_height_m,
        n_beds=n_beds,
        regen_ethanol_vapor_flow_kg_s=regen_flow_kg_s,
        regen_sensible_duty_kW=sensible_duty_kW,
        regen_latent_duty_kW=latent_duty_kW,
        regen_heater_duty_kW=regen_duty_kW,
        meets_bis_spec=outlet_water_vol_frac <= BIS_IS_15464_MAX_WATER_VOL_FRAC,
        height_to_diameter_ratio=aspect_ratio,
        recommend_parallel_vessels=recommend_parallel,
    )
